[package]
name = "auto-ui-adapter-rust-chatbot"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
auto-ui-artifacts = { path = "../auto-ui-artifacts" }
auto-ui-core = { path = "../auto-ui-core" }

chrono.workspace = true
clap.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true

[dev-dependencies]
auto-ui-driver-x11 = { path = "../auto-ui-driver-x11" }

[target.'cfg(target_os = "macos")'.dev-dependencies]
auto-ui-driver-macos = { path = "../auto-ui-driver-macos" }
