[package]
name = "auto-ui"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
auto-ui-adapter-gpui = { path = "../auto-ui-adapter-gpui" }
auto-ui-adapter-rust-chatbot = { path = "../auto-ui-adapter-rust-chatbot" }
auto-ui-artifacts = { path = "../auto-ui-artifacts" }
auto-ui-core = { path = "../auto-ui-core" }
clap.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
